### PR TITLE
media-libs/oidn: apply Gentoo-related fixes for hip suport

### PR DESCRIPTION
**Pull request by AngryLoki**

### CODE REVIEW

**Comment by DarkDefender** [comment]
I noticed that you don't need to manually specify the clang path as `hipcc` seems like is what actually should be used (it is just a clang wrapper that ships with the hip package). However you can get the path to this in cmake with `find_package(hip REQUIRED)`.
Here is an example patch:

```
diff --git a/devices/CMakeLists.txt b/devices/CMakeLists.txt
index 4e25cf2..a1b863d 100644
--- a/devices/CMakeLists.txt
+++ b/devices/CMakeLists.txt
@@ -79,54 +79,8 @@ if(OIDN_DEVICE_HIP)
     message(FATAL_ERROR "Building with HIP support requires Ninja or Make")
   endif()
 
-  # Find ROCm
-  if(NOT ROCM_PATH)
-    if(WIN32)
-      set(_rocm_search_paths "$ENV{PROGRAMFILES}/AMD/ROCm/*")
-    else()
-      set(_rocm_search_paths "/opt/rocm")
-    endif()
-
-    find_path(ROCM_PATH
-      NAMES
-        bin/hipconfig
-      HINTS
-        $ENV{ROCM_PATH}
-      PATHS
-        ${_rocm_search_paths}
-      NO_DEFAULT_PATH
-      DOC
-        "ROCm installation path."
-    )
-    mark_as_advanced(ROCM_PATH)
-
-    if(ROCM_PATH)
-      message(STATUS "Found ROCm: ${ROCM_PATH}")
-    else()
-      message(FATAL_ERROR "Failed to find ROCm.\nBuilding with HIP support requires ROCm. Please set the ROCM_PATH variable.")
-    endif()
-  endif()
-
-  # Find HIP compiler
-  find_program(OIDN_DEVICE_HIP_COMPILER
-    NAMES
-      clang++
-    HINTS
-      ${ROCM_PATH}
-    PATH_SUFFIXES
-      bin
-      llvm/bin
-    NO_DEFAULT_PATH
-    REQUIRED
-    DOC
-      "HIP compiler."
-  )
-  mark_as_advanced(OIDN_DEVICE_HIP_COMPILER)
-
-  # Add ROCm to CMAKE_PREFIX_PATH
-  set(_hip_prefix_path CMAKE_PREFIX_PATH)
-  list(APPEND _hip_prefix_path ${ROCM_PATH}/hip ${ROCM_PATH})
-  list(JOIN _hip_prefix_path "|" _hip_prefix_path_str)
+  find_package(hip REQUIRED)
+  set(OIDN_DEVICE_HIP_COMPILER ${HIP_HIPCC_EXECUTABLE} CACHE INTERNAL "")
 
   ExternalProject_Add(OpenImageDenoise_device_hip
     PREFIX hip
@@ -135,9 +89,7 @@ if(OIDN_DEVICE_HIP)
     STAMP_DIR hip/stamp
     LIST_SEPARATOR |
     CMAKE_CACHE_ARGS
-      -DCMAKE_PREFIX_PATH:STRING=${_hip_prefix_path_str}
       -DCMAKE_CXX_COMPILER:FILEPATH=${OIDN_DEVICE_HIP_COMPILER}
-      -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}
       -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
       -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/hip/preinstall
       -DCMAKE_INSTALL_BINDIR:PATH=${CMAKE_INSTALL_BINDIR}
```

I think this is better as you don't have to pass the `ROCM_PATH` variable nor the Clang compiler.
What do you think?

**Comment by AngryLoki** [comment]
`ROCM_PATH` was documented in https://github.com/OpenImageDenoise/oidn?tab=readme-ov-file#cmake-configuration and is intended way to set path to ROCm libraries. It is marked as "autodetected by default", but it does not try to search in /usr. But setting path to clang and `-DROCM_PATH=/usr` easier to maintain, IMO.

There is also a theory, that eventually hipcc will be deprecated (idk, maybe oidn thought about this). There are still minor differences between clang and hipcc behavior, but vanilla Clang already knows how to detect ROCm path (just does it wrong - https://github.com/llvm/llvm-project/issues/78344), but after this fix it will behave like hipcc.

**Comment by DarkDefender** [comment]
What are the upsides of using clang directly?
I'm just asking as the rocm.eclass seems to suggest just passing hipcc instead.

I'm just asking as it seems simpler to me to just rely on hipcc being there as part of the hip package.
Instead of including the llvm slot and detection logic.

**Comment by AngryLoki** [comment]
I don't know why you removed `-DGPU_TARGETS` part from the patch, but it is still required. Without it hipcc may attempt to detect current GPU, but will fail due to sandbox restrictions (or for the case of oidn it will build for some nonconfigurable list of GPUs).

There are no major upsides of pure clang, it just makes patch smaller, and smaller patches are easier to maintain.

**Comment by DarkDefender** [comment]
Fair enough :)

**Pull request merged**
